### ISSUE TITLE
RichEditor uses unspecified Dp

### ISSUE THREAD

**Issue by Him188** [project-solvo/solvo#3]

**Comment by Him188** [comment]
"IllegalStateException: Size is unspecified
    at _Size___get_width__impl__58y75t (webpack-internal:///./kotlin/compose-multiplatform-core-ui-geometry.js:954:13)
    at protoOf.draw_j25tpb_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:3234:27)
    at protoOf.draw_xi64lu_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:25710:14)
    at drawContainedDrawModifiers (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:30300:17)
    at protoOf.draw_lhjy7e_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:31275:7)
    at protoOf.performDraw_1j48lz_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:22912:41)
    at drawContainedDrawModifiers (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:30297:13)
    at eval (webpack-internal:///./kotlin/compose-multiplatform-core-ui.js:30632:7)
    at protoOf.observe_3gku70_k$ (webpack-internal:///./kotlin/compose-multiplatform-core-runtime.js:28064:25)
    at eval (webpack-internal:///./kotlin/compose-multiplatform-core-runtime.js:35194:34)"
